# Урок 1. Введение в Python

### История языка

Python был разработан в конце 1989г. Гуидо ван Россумом (Guido van Rossum) во время рождественских каникул, когда его исследовательская лаборатория была закрыта и ему просто некуда было деваться. Он позаимствовал многие средства программирования, присущие другим языкам.

<img width = '200px' src="images/lesson_1/1200px-Guido_van_Rossum_OSCON_2006.jpg">

In [17]:
# Разные типы разметки ячеек
# Command Mode|Edit mode

### Философия Python

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# Основы Python

Для нас важно помнить, что Python:

- интерпретируемый;
- с динамической типизацией;
- имеет возможности как для ООП, так и для ФП.

Официальная документация Python доступна по ссылке https://docs.python.org/3/.

### Пример программы

In [2]:
import time

def learn_python_function(on_lecture = True):
    print("Продолжать изучать анализ данных с помощью Python?")

    dark = {
        1: 16, 2: 17,
        3: 18, 4: 19,
        5: 19, 6: 20,
        7: 20, 8: 19,
        9: 18, 10: 17,
        11: 16, 12: 16
        }

    light = {
        1: 8, 2: 7,
        3: 6, 4: 5,
        5: 4, 6: 4,
        7: 4, 8: 5,
        9: 6, 10: 6,
        11: 7, 12: 8
        }

    time_now = time.localtime()

    if time_now.tm_hour >=dark[time_now.tm_mon] or time_now.tm_hour < light[time_now.tm_mon]:
        if on_lecture == False:
            print("Нет, пора немного отдохнуть!")
        else:
            print("Продолжай изучать на лекции!")
    else:
        print("Да, продолжай!")

learn_python_function(True)        

Продолжать изучать анализ данных с помощью Python?
Продолжай изучать на лекции!


- блоки в Python всегда выделены отступом;
- двоеточие (:) важно, поскольку вводит новый блок кода, который должен быть смещен на один отступ вправо;
- каждый блок кода может содержать любое количество вложенных блоков, которые также отделяются отступами.

### Комментарии

In [3]:
# это первый комментарий
spam = 1  # а это второй комментарий
          # ... а сейчас третий!
text = "# Это не комментарий, потому что он внутри кавычек."

### Вывод данных

In [4]:
print("Всем привет!")
print("A", "B", "C")
print("A", "B", "C", sep="#")

Всем привет!
A B C
A#B#C


### Числа

In [8]:
2+2

4

In [9]:
50 - 5*6

20

In [10]:
(50 - 5*6) / 4

5.0

In [11]:
8 / 5  # деление всегда возвращает число с плавающей точкой

1.6

Целые числа (например, 2, 4, 20) имеют тип int, те, что с дробной частью, (e.g. 5.0, 1.6) имеют тип float.

Деление (/) всегда возвращает float. По умолчанию, во втором питоне деление целого числа на целое даёт целочисленное деление. Чтобы сделать целочисленное деление (отметая дробную часть) вы можете использовать оператор //; чтобы посчитать остаток от деления, вы можете использовать %:

In [12]:
17 // 3

5

In [13]:
17 % 3

2

In [14]:
5 ** 2 #возведение в степень

25

Знак равенства (=) используется для присвоения значения переменной.

In [15]:
width = 20
height = 30
S = width * height
S

600

Присутствует полная поддержка операций с плавающей точкой; операции над операндами смешанного типа конвертируют целочисленный операнд в число с плавающей запятой:

In [16]:
3 * 3.75 / 1.5

7.5

В дополнении к int и float Python поддерживает другие типы чисел, такие как Decimal и Fraction. Python также имеет встроенную поддержку для комплексных чисел, и использует суффикс j или J для указания мнимой части (например, 3+5j).

### Строки

Помимо чисел, Python может работать со строками, которые, в свою очередь, могут быть описаны различными способами. Строки могут быть заключены в одинарные ('...') или двойные кавычки ("..."), без разницы; \ может быть использован для экранирования кавычек:

In [17]:
print('spam eggs') 
print('doesn\'t') 
print("doesn't")
print('"Yes," he said.')

spam eggs
doesn't
doesn't
"Yes," he said.


Строковые литералы могут занимать несколько строк. Один из способов сделать это — тройные кавычки: """...""" или '''...'''. Концы строк автоматически включаются в строку, но возможно избежать этого добавлением \ в конце строки. Следующий пример:

In [18]:
print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")

Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to



Строки могут быть конкатенированы (соединены вместе) с помощью оператора +, и повторены с помощью *:

In [19]:
3 * 'un' + 'ium'

'unununium'

In [20]:
print('Hello, {}!'.format('Vasya'))
print('{0}, {1}, {2}'.format('a', 'b', 'c'))

Hello, Vasya!
a, b, c


### Модель данных

Часто можно услышать утверждение о том, что в питоне **все является объектом**. Утверждение верное, причем у каждого объекта есть:
- сущность (identity);
- тип (type);
- значение (value).

Сущность (identity) объекта не меняется после создания, можно думать о ней как об адресе в памяти компьютера.

Например, если мы пишем: `a = 42` создается объект типа int со значением 42. Сущность (identity) объекта в таком случае - это его адрес в памяти, 'а' - имя указателя на этот адрес.

Для того, чтобы посмотреть на объект с каким идентификатором ссылается данная переменная, можно использовать функцию id().

In [6]:
a = 4
b = 4

In [7]:
id(a)

1499683984

In [8]:
id(b)

1499683984

In [9]:
a is b

True

In [10]:
a == b

True

Рассмотрим другой пример.

In [11]:
c = [1,2,3]
d = [1,2,3]

In [12]:
id(c)

2482529554248

In [13]:
id(d)

2482528753416

In [14]:
c == d

True

In [15]:
c is d

False

<img width = '350px' src="images/lesson_1/wat.jpg">

В Python существуют <B>изменяемые</B> и <B>неизменяемые</B> типы.

К <B>неизменяемым</B> (immutable) типам относятся: целые числа (int),  числа с плавающей точкой (float), комплексные числа (complex), логические переменные (bool), кортежи (tuple), строки (str) и неизменяемые множества (frozen set).

К <B>изменяемым</B> (mutable) типам относятся: списки (list), множества (set), словари (dict).

При создании переменной, вначале создается объект, который имеет уникальный идентификатор, тип и значение, после этого переменная может ссылаться на созданный объект.

Неизменяемость типа данных означает, что созданный объект больше не изменяется. 

Более подробно про типы данных можно прочитать https://docs.python.org/3/library/stdtypes.html

In [1]:
#Неизменяемый тип данных
a = 5

b = a

b += 1

a

5

In [3]:
#Изменяемый тип данных
a = [1,2,3]

b = a

b.append(4)

a

[1, 2, 3, 4]

Неизменяемые объекты передаются по *значению*. Это значит, что при изменении значения переменной будет создан новый объект.

Изменяемые объекты передаются по *ссылке*. Это значит, что при изменении значения переменной объект будет изменен. 

### Условные операторы 

In [31]:
a = 1
if a > 2:
   print("H")
else:
   print("L")

L


In [32]:
a = int(input("введите число:"))
if a < 0:
   print("Neg")
elif a == 0:
   print("Zero")
else:
   print("Pos")

введите число:2
Pos


### Операторы цикла

Оператор цикла while  выполняет указанный набор инструкций до тех пор, пока условие цикла истинно.

In [33]:
a = 0
while a < 3:
   print("A")
   a += 1

A
A
A


Оператор <B>break</B> предназначен для досрочного прерывания работы цикла while.

In [34]:
a = 0
while a >= 0:
   if a == 3:
       break
   a += 1
   print("A")

A
A
A


Оператор <B>continue</B>  запускает цикл заново, при этом код, расположенный после данного оператора, не выполняется.

In [35]:
a = -1
while a < 10:
   a += 1
   if a >= 7:
       continue
   print("A")

A
A
A
A
A
A
A


Оператор <B>for</B>  выполняет указанный набор инструкций заданное количество раз, которое определяется количеством элементов в наборе.

In [36]:
for i in range(5):
   print("Hello")

Hello
Hello
Hello
Hello
Hello


### Списки

Список (list) – это структура данных для хранения объектов различных типов. Размер списка не статичен, его можно изменять. Список по своей природе является изменяемым типом данных. 

 При его создании в памяти резервируется область, которую можно условно назвать некоторым “контейнером”, в котором хранятся ссылки на другие элементы данных в памяти. В отличии от таких типов данных как число или строка, содержимое “контейнера” списка можно менять.

 <img height = '200px' src="images/lesson_1/python-lesson3-2-1.png">

In [37]:
a = []
b = list()
с = [1, 2, 3]

In [5]:
#копирование списка
a = [1, 3, 5, 7]
b = a
# b = list(a)
b = a.copy()
print(a)
print(b)

[1, 3, 5, 7]
[1, 3, 5, 7]


In [3]:
a = [1, 3, 5, 7]
b = a
b[3] = 15
a[1] = 10
print(a)
print(b)

[1, 10, 5, 15]
[1, 10, 5, 15]


In [40]:
#Добавление элементов в список
a = []
a.append(3)
a.append("hello")
a

[3, 'hello']

In [8]:
#Удаление элементов
a.remove(3)
print(a)
del a[0]
print(a)

ValueError: list.remove(x): x not in list

In [9]:
6**8


1679616

In [4]:
#Доступ к элементам списка
a = [3, 5, 7, 10, 3, 2, 6, 0]
print(a[2])
print(a[-1])
print(a[1:4])

7
0
[5, 7, 10]


In [6]:
#Методы списков 
#Для удобного воспроизведения есть шорткат ctrl+shift+-
a = [1, 2]
a.append(3)
print(a)

[1, 2, 3]


In [4]:
a = [1, 2]
b = [3, 4]
a.extend(b)
print(a)

[1, 2, 3, 4]


In [6]:
a = [1, 2]
a.insert(0, 5)
print(a)

a = [1, 2, 3]
a.remove(1)
print(a)

a = [1, 2, 3, 4, 5]
print(a.pop(2))
print(a.pop())
print(a)

a.clear()
print(a)

a = [1, 2, 3, 4, 5]
a.index(4)

print(a.count(2))

a.sort()
print(a)

a.reverse()
print(a)

[5, 1, 2]
[2, 3]
3
5
[1, 2, 4]
[]
1
[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


### Абстракция списков

In [44]:
n = int(input())
a = []
for i in range(n):
    a.append(i)
print(a)

2
[0, 1]


In [45]:
print([i for i in range(int(input()))])

2
[0, 1]


### Кортеж

Кортеж (tuple) – это неизменяемая структура данных, которая по своему подобию очень похожа на список. 

In [46]:
b = (1, 2, 3)
print(b)

b[1] = 15

(1, 2, 3)


TypeError: 'tuple' object does not support item assignment

Существует несколько причин, по которым стоит использовать кортежи вместо списков.

- Одна из них – это обезопасить данные от случайного изменения.
- Во-вторых – прирост производительности, который связан с тем, что кортежи работают быстрее, чем списки (т.е. на операции перебора элементов и т.п. будет тратиться меньше времени). Важно также отметить, что кортежи можно использовать в качестве ключа у словаря.

In [ ]:
a = tuple()
b = ()
c = tuple([1,2,3])
d = (1,2,3,4,5)

### Словари

Словарь (dict) представляет собой структуру данных (которая ещё называется ассоциативный массив), предназначенную для хранения произвольных объектов с доступом по ключу. Данные в словаре хранятся в формате ключ – значение.

In [ ]:
d1 = dict()
d2 = {}
d3 = dict(Ivan="manager", Mark="worker")

In [87]:
d1 = {"Russia":"Moscow", "USA":"Washington"}
d1["China"]="Beijing"
d1

{'China': 'Beijing', 'Russia': 'Moscow', 'USA': 'Washington'}

# del d1["China"]

In [5]:
#Методы словарей
d2 = {"A1":"123", "A2":"456"}
d2.clear()
print(d2)

d2 = {"A1":"123", "A2":"456"}
d3 = d2.copy()

print(d3.get("A1"))

print(d3.items())

print(d3.keys())

print(d3.values())

print(d3.pop("A2"))
print(d3)
print(d3.popitem())
print(d3)

{}
123
dict_items([('A1', '123'), ('A2', '456')])
dict_keys(['A1', 'A2'])
dict_values(['123', '456'])
456
{'A1': '123'}
('A1', '123')
{}


### Немного про функции

Функция в python - объект, принимающий аргументы и возвращающий значение. Обычно функция определяется с помощью инструкции **def**.

In [66]:
def add(x, y):
#     pass
    return x + y

In [67]:
add(5,6)

11

In [2]:
def func(a, b, c=2): # c - необязательный аргумент
    return a + b + c

In [3]:
func(3,5)

10

Функция также может принимать переменное количество позиционных аргументов (аргументы, передаваемые в вызов в определённой последовательности (на определённых позициях), без указания их имён), тогда перед именем ставится *.

In [70]:
def func(*args):
    return args

In [71]:
func(1, 2, 3, 'abc')

(1, 2, 3, 'abc')

Функция может принимать и произвольное число именованных аргументов (аргументы, передаваемые в вызов при помощи имени), тогда перед именем ставится **.

In [72]:
def func(**kwargs):
    return kwargs

In [73]:
func(a=1, b=2, c=3)

{'a': 1, 'b': 2, 'c': 3}

https://colab.research.google.com/drive/1dkvnHbah-WDE3mQyI9rsCrhLbWbQVK-d

# Библиотека NumPy

**Numpy** - пакет для векторизованных вычислений, добавляющий поддержку больших многомерных массивов и матриц, вместе с большой библиотекой высокоуровневых математических функций для операций с этими массивами.

Одна из ключевых особенностей NumPy - объект ndarray для представления N-мерного массива; это быстрый и гибкий контейнер для хранения больших наборов данных в Python. ndarray - это обобщенный многомерный контейнер для однородных данных, т. е. в нем могут храниться только элементы одного типа. Под «многомерностью» массива мы понимаем то, что у него может быть несколько измерений или осей.

In [7]:
import numpy as np

In [3]:
#создание массива
datal = [ 6, 7.3, 5, 8, 0, 1]
arrl = np.array(datal) 
arrl

array([6. , 7.3, 5. , 8. , 0. , 1. ])

In [4]:
arrl.shape

(6,)

In [5]:
arrl.dtype

dtype('float64')

In [5]:
np.ones((2,2))

NameError: name 'np' is not defined

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<img width = '500px' src="images/lesson_1/elsp_0105.png">

In [9]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Можно явно преобразовать, или привести массив одного типа к другому, воспользовавшись методом as type: 

In [11]:
numeric_strings = np.array(['1.25', '-9.6', '42']) 
numeric_strings.astype(float) 

array([ 1.25, -9.6 , 42.  ])

### Операции между массивами и скалярами

In [14]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 

In [15]:
arr.shape

(2, 3)

In [16]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [17]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

### Случайные массивы


In [19]:
np.random.randn(3,2)

array([[ 1.65953006,  0.21858134],
       [ 0.45937131, -1.99453659],
       [-0.97451502, -0.65750757]])

In [20]:
np.random.randint(0, 1000, 4)

array([123, 829, 670,   9])

### Индексирование


Схоже с индексированием списков.

<img width = '500px' src="images/lesson_1/Screen-Shot-2017-10-28-at-10.40.10-PM-768x405.png">

In [22]:
np.arange(15)[8:12]

array([ 8,  9, 10, 11])

In [23]:
#многомерные массивы
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [24]:
arr2d[0, 2] 

3

In [25]:
arr2d[0][2] 

3

In [12]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
arr3d[1][1][2]
# arr3d[1,1,2]

12

In [14]:
#булевое индексирование
names = np.array(['Bob', 'Joe', 'Will', 'Воb', 'Will', 'Joe', 'Joe'])
names == 'Bоb'

array([False, False, False, False, False, False, False])

In [15]:
mask = (names == 'Воb') | (names == 'Will') 
mask

array([False, False,  True,  True,  True, False, False])

In [16]:
names[mask]

array(['Will', 'Воb', 'Will'], dtype='<U4')

### Запись логических условий в виде операций с массивами 

In [18]:
xarr =  np.array ( [ 1., 1, 1.2, 1., 3, 1.4, 1.5]) 
aarr =  np.array ( [ 2., 3, 4.2, 1., 2, 4.4, 5.5]) 
cond =  np.array ( [ True, False, False, True, True, False, False])

In [19]:
result = [(х if с else у) for х, у, с in zip(xarr, aarr, cond)] 
result

[1.0, 3.0, 4.2, 1.0, 3.0, 4.4, 5.5]

In [20]:
result = np.where(cond, xarr, aarr) 
result

array([1. , 3. , 4.2, 1. , 3. , 4.4, 5.5])

### Математические и статистические операции

In [34]:
arr = np.random.randn(5, 4) 
arr

array([[-0.00596852, -0.26063004, -0.64562329,  1.18397813],
       [ 0.37932538,  0.16275316, -0.47999506,  0.16092507],
       [ 1.5993822 ,  0.45838581,  1.49774829, -0.81789182],
       [ 1.26446651, -1.59557461,  1.43535513,  2.00361282],
       [ 0.39963166, -0.90393379,  1.04173045, -0.2928276 ]])

In [35]:
arr.shape

(5, 4)

In [36]:
arr.mean()

0.3292424943769746

In [38]:
np.exp(arr)

array([[0.99404925, 0.77056594, 0.52433563, 3.26734633],
       [1.46129843, 1.17674619, 0.61878645, 1.17459695],
       [4.94997338, 1.58151906, 4.47160897, 0.44136114],
       [3.54120305, 0.20279197, 4.20113668, 7.41579971],
       [1.49127531, 0.40497344, 2.83411708, 0.74615077]])

In [39]:
arr.sum(axis = 0)

array([ 3.63683723, -2.13899947,  2.84921552,  2.2377966 ])